---
version: "2"
exclude_patterns:
  - "bin/"
  - "bootstrap/"
  - "build/"
  - "config/"
  - "database/"
  - "docker/"
  - "docs/build/"
  - "docs/cache/"
  - "docs/sami/"
  - "homestead/"
  - "node_modules/"
  - "public/"
  - "storage/"
  - "tests/"
  - "vendor/"
  - "resources/"
  - "config/"
  - "**/Behat/"
  - "**/Resources/"
  - "**/Tests/"
  - "**/cache/"
  - "**/node_modules/"
  - "**/tests/"
  - "**/vendor/"
  - ".git/"
  - "**/*.swp"
plugins:
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - "src/**/*.php"
        - "tests/**/*.php"
        - "app/**/*.php"

  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
