language: php
php:
  - '7.2'
  - '7.3'
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE cruftman;"
  - mysql -e "CREATE USER cruftman IDENTIFIED BY 'cruftman';"
  - mysql -e 'GRANT ALL ON cruftman.* TO cruftman;'
install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml.dist
after_success:
  - curl -s https://codecov.io/bash | bash
