version: 2.1

jobs:
  example:
    docker:
      - image: circleci/python:3.7


    steps:
      - checkout

      - run:
          name: Setup virtualenv
          command: echo "Hello world!"


workflows:
  version: 2.1

  examples:
    jobs:
      - example
