version: '3.2'
services:
  php:
    build:
      context: php
      args:
        CRUFT_IMG: "korowai/php:${CRUFT_PHP_TAG:-cli}"
        CRUFT_UID: "${CRUFT_UID:-6789}"
        CRUFT_GID: "${CRUFT_GID:-6789}"
    volumes:
      - ..:${CRUFT_CODE:-/code}
    user: "${CRUFT_UID:-6789}:${CRUFT_GID:-6789}"

  test:
    build:
      context: php
      args:
        CRUFT_IMG: "korowai/php:${CRUFT_PHP_TAG:-cli}"
        CRUFT_UID: "${CRUFT_UID:-6789}"
        CRUFT_GID: "${CRUFT_GID:-6789}"
    depends_on:
      - ldap-service
      - http-service
      - db-service
    volumes:
      - ..:${CRUFT_CODE:-/code}
    user: "${CRUFT_UID:-6789}:${CRUFT_GID:-6789}"
    entrypoint: [ "dockerize", "-wait", "tcp://ldap-service:389",
                               "-wait", "tcp://db-service:3306",
                               "-timeout", "600s" ]

  http-service:
    build:
      context: http
      args:
        CRUFT_IMG: "korowai/php:${CRUFT_APACHE_TAG:-apache}"
        CRUFT_UID: "${CRUFT_UID:-6789}"
        CRUFT_GID: "${CRUFT_GID:-6789}"
    environment:
      - APACHE_DOCUMENT_ROOT=${CRUFT_CODE:-/code}/public
    ports:
      - "${CRUFT_HTTP_PORT:-8000}:80"
    volumes:
      - ..:${CRUFT_CODE:-/code}

  ldap-service:
    build:
      context: ldap
      args:
        CRUFT_IMG: "korowai/openldap:${CRUFT_OPENLDAP_TAG:-latest}"
        CRUFT_UID: "${CRUFT_UID:-6789}"
        CRUFT_GID: "${CRUFT_GID:-6789}"
    command: [ --copy-service, --loglevel, debug ]
    volumes:
      - ../tests/resources/ldap/acl.ldif:/container/service/slapd/assets/config/bootstrap/ldif/99-acl.ldif
      - ../tests/resources/ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/99-bootstrap.ldif

  db-service:
    build:
      context: db
      args:
        CRUFT_IMG: "mariadb:${CRUFT_MARIADB_TAG:-latest}"
        CRUFT_UID: "${CRUFT_UID:-6789}"
        CRUFT_GID: "${CRUFT_GID:-6789}"
    environment:
      - MYSQL_ROOT_PASSWORD=${CRUFT_MYSQL_ROOT_PASSWORD:-cruftman}
      - MYSQL_DATABASE=${CRUFT_MYSQL_DATABASE:-cruftman}
      - MYSQL_USER=${CRUFT_MYSQL_USER:-cruftman}
      - MYSQL_PASSWORD=${CRUFT_MYSQL_USER:-cruftman}
    ports:
      - "${CRUFT_DB_PORT:-8306}:3306"
    volumes:
      - ..:${CRUFT_CODE:-/code}
